# spring.application.name=oms
spring.application.name=oms

# Database
spring.datasource.url=jdbc:mysql://hayabusa.proxy.rlwy.net:53486/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=DsxjZwUNAJceoavNouDadWJZqfaCEsLA

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080